name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup environment
        run: python3 -m pip install poetry

      - name: pytest
        run: make pytest

  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup environment
        run: python3 -m pip install poetry

      - name: black
        run: make black-check

      - name: pylint
        run: make pylint

      - name: pycodestyle
        run: make pycodestyle

      - name: mypy
        run: make mypy
